version: '1.0'
services:
  app:
    image: karencgoncalves/watcher-app:1.0
    links:
      - 'db'
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
