version: '1.0'
services:
  app:
    build: ./app/
    links:
      - 'db'
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 123
      MYSQL_USER: karen
      MYSQL_DATABASE: watcher
    volumes:
      - ./db:/docker-entrypoint-initdb.d